name: Update Jira Issue with README Content

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read README content
      id: read-readme
      run: |
        README_CONTENT=$(cat README.md)
        echo "README content: $README_CONTENT"
        echo "::set-output name=content::$README_CONTENT"

    - name: Update Jira Issue with README content
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_ISSUE_KEY: ${{ secrets.JIRA_ISSUE_KEY }}
      run: |
        echo "Updating issue key: $JIRA_ISSUE_KEY with content: ${{ steps.read-readme.outputs.content }}"
        UPDATE_RESPONSE=$(curl -s -u $JIRA_EMAIL:$JIRA_API_TOKEN \
          -X PUT \
          --data '{ "fields": { "description": "'"${{ steps.read-readme.outputs.content }}"'" } }' \
          -H "Content-Type: application/json" \
          $JIRA_BASE_URL/rest/api/2/issue/$JIRA_ISSUE_KEY)
        
        echo "Update issue response: $UPDATE_RESPONSE"
