name: Update Jira Issue

on:
  push:
    branches:
      - main

jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Jira Issue
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_ISSUE_KEY: ${{ secrets.JIRA_ISSUE_KEY }}
      run: |
        curl -D- -u $JIRA_EMAIL:$JIRA_API_TOKEN \
        -X PUT \
        --data '{ "fields": { "description": "Code has been pushed to the main branch." } }' \
        -H "Content-Type: application/json" \
        $JIRA_BASE_URL/rest/api/2/issue/$JIRA_ISSUE_KEY
